In [2]:
cd /work/FAC/FBM/DBC/cdessim2/default/dmoi/projects/aars/aarsonline.github.io

/work/FAC/FBM/DBC/cdessim2/default/dmoi/projects/aars/aarsonline.github.io


In [3]:
datadir = '/work/FAC/FBM/DBC/cdessim2/default/dmoi/projects/aars/aarsonline.github.io/struct_trees/'


In [6]:
#run pdbfixer on all structs
from Bio import PDB
from pdbfixer import PDBFixer
from openmm.app import PDBFile
import glob
import sys
import tqdm
import pandas as pd
import multiprocessing as mp
#argument parser for the script 
from concurrent.futures import TimeoutError
from pebble import ProcessPool, ProcessExpired
import os
import glob

In [7]:
structsc1 = glob.glob(datadir+'c1/structs/*.pdb')
print('c1' ,  len(structsc1))
structsc2 = glob.glob(datadir+'c2/structs/*.pdb')
print('c2' ,  len(structsc2))
structs3 = glob.glob(datadir+'CRIMVLG/structs/*.pdb')
print('CRIMVLG' ,  len(structs3))

structs = structsc1 + structsc2 + structs3
print(len(structs))

c1 251
c2 298
CRIMVLG 47
596


In [8]:
#make directory for the fixed structures
os.makedirs(datadir+'c1/structs_fixed', exist_ok=True)
os.makedirs(datadir+'c2/structs_fixed', exist_ok=True)
os.makedirs(datadir+'CRIMVLG/structs_fixed', exist_ok=True)


In [9]:
def prepchain( pdbfile , chain=None, savepath=None ,unid='',  verbose = False):
    assert savepath is not None
    
    try:
        #parse the pdb file
        parser = PDB.PDBParser()
        structure = parser.get_structure(unid, pdbfile)
        if chain:
            chainID = chain
        else:
            chainID = list(structure[0].get_chains())[0].get_id()
        chain_A = structure[0][chainID]
    except:
        print("error")
        return None
    if chain_A:
        io = PDB.PDBIO()
        io.set_structure(chain_A)
        io.save(savepath)
        fixer = PDBFixer(filename=savepath)
        fixer.findNonstandardResidues()
        fixer.replaceNonstandardResidues()
        fixer.removeHeterogens(True)
        fixer.findMissingResidues()
        fixer.findMissingAtoms()
        fixer.addMissingAtoms()
        #fixer.addMissingHydrogens(7.0)
        PDBFile.writeFile(fixer.topology, fixer.positions, open(savepath, 'w'))
        return None


fix_structs = False
if fix_structs:
	with ProcessPool() as pool:
		futures = [ pool.schedule( prepchain,  ( pdb , None , pdb.replace('structs', 'structs_fixed' ) , '' , False ) , timeout = 120) for pdb in structs  ]
		for future in tqdm.tqdm(futures, total=len(structs)):
			try:
				results = future.result()
			except TimeoutError as error:
				print("unstable_function took longer than %d seconds" % error.args[1])
			except ProcessExpired as error:
				print("%s. Exit code: %d" % (error, error.exitcode))
			except Exception as error:
				print("unstable_function raised %s" % error)
				print(error.traceback)  # Python's traceback of remote process
		pool.close()
		pool.join()



In [10]:
import pandas as pd
import Bio.PDB
import numpy as np
import os
import tqdm

def extract_core(resdf , outfile,  hitthresh = .8 ,minthresh = .6, corefolder = 'core_structs/' , structfolder = 'structs/' , cterfolder = 'cter_structs/' , nterfolder = 'nter_structs/'  , folder = None):
	"""

	Extract a core of structures from a results file

	Parameters
		resdf: path to results file
		outfile: path to output file
		hitthresh: proportion of structures that need to map to a residue for it to be included in the core
		minthresh: if no residues meet the hitthresh, the minimum proportion of structures that need to map to a residue for it to be included in the core
		corefolder: name of folder to output core structures to
		structfolder: name of folder to find structures in
		cterfolder: name of folder to find cter structures in
		nterfolder: name of folder to find nter structures in


	"""
	
	#read all results
	if folder is None:
		folder =''.join([ sub + '/' for sub in resdf.split('/')[:-1] ])
	
	print(folder)
	resdf = pd.read_table(resdf, header = None)
	resdf.columns = 'query,target,fident,alnlen,mismatch,gapopen,qstart,qend,tstart,tend,evalue,bits,lddt,lddtfull,alntmscore'.split(',')

	print('extracting core')
	print('hitthresh: ' + str(hitthresh))
	print('minthresh: ' + str(minthresh))

	print(resdf.head(), len(resdf['query'].unique()))
	#map hits to each struc
	hits = {}
	nqueries = len(resdf['query'].unique())
	#proportion of structures that need to map to a residue fo
	with tqdm.tqdm(total=len(resdf['query'].unique())) as pbar:
		for i,q in enumerate(resdf['query'].unique()):
			sub = resdf[resdf['query'] == q]
			hitvec = np.zeros((1,max(sub['qend'])) )
			for idx,r in sub.iterrows():
				hitvec[0,r['qstart']:r['qend']] = hitvec[0,r['qstart']:r['qend']]+1
			hitvec /= nqueries
			core = np.where(hitvec>hitthresh)[1]
			try:
				hits[q]= { 'min': np.amin(core), 'max': np.amax(core) }
			except:
				#be more lenient...
				subthresh = np.amax(hitvec)
				print(hitvec, sub, 'be careful, non homologous sequences may have enterred the dataset!')
				if subthresh>=minthresh:
					print('new core threst set at ' + str(subthresh) )
					core = np.where(hitvec>=subthresh)[1]
					hits[q]= { 'min': np.amin(core), 'max': np.amax(core)}
					print(q , 'added')
				else:
					print(q , 'rejected')
			pbar.set_description('processed: %d' % (1 + i))
			pbar.update(1)
	#make core struct folder
	os.makedirs(folder+corefolder , exist_ok = True)
	os.makedirs(folder+cterfolder , exist_ok = True)
	os.makedirs(folder+nterfolder , exist_ok = True)
	#parse each struct and output core to folder 
	parser = Bio.PDB.PDBParser()
	with tqdm.tqdm(total=len(hits)) as pbar:
		for i,q in enumerate(hits):
			if not q.endswith('.pdb'):
				qfile = q + '.pdb'
			else:
				qfile = q
			if '/' in q:
				qfile = qfile.split('/')[-1]

			struct = parser.get_structure(q.split('.')[0], structfolder+qfile )

			#zero based indexing...
			struct_core = Bio.PDB.Dice.extract( struct ,'A' , hits[q]['min']+1 , hits[q]['max']+1 ,folder+corefolder+qfile  )
			
			struct_core = Bio.PDB.Dice.extract( struct ,'A' , 0, hits[q]['min']+1  ,folder+nterfolder+q  )
			#select from max to end
			struct_core = Bio.PDB.Dice.extract( struct ,'A' , hits[q]['max']+1 , len(struct[0]['A'])  ,folder+cterfolder+qfile  )

			hits[q]['len'] = [ len(chain) for model in struct for chain in model ][0]

			pbar.set_description('processed: %d' % (1 + i))
			pbar.update(1)


	hitsdf = pd.DataFrame.from_dict( hits , orient='index'  )
	hitsdf.to_csv(outfile)
	return folder +'struct_cores.csv'




In [11]:
import sys
import os

sys.path.append('../../snake_tree/src')
import numpy as np
import pandas as pd
import foldseek2tree


In [42]:

def structblob2tree(input_folder, outfolder, overwrite = False,
             fastmepath = 'fastme', quicktreepath = 'quicktree' , 
         foldseekpath = 'foldseek' , delta = 0.0001 ,
       correction = False , kernels = ['fident' , 'lddt' , 'alntmscore' ] , core = False 
       , hittresh = .8 , minthresh = .6 , swapids = False):
    '''
    run fold tree pipeline for a folder of pdb files
    
    Parameters
    ----------
    input_folder : str
        path to folder with pdb files   
    outfolder : str
        path to output folder   
    overwrite : bool
        overwrite existing foldseek output  
    fastmepath : str    
        path to fastme executable
    quicktreepath : str 
        path to quicktree executable
    foldseekpath : str  
        path to foldseek executable 
    delta : float   
        small number to replace negative branch lengths with, default is .0001
    correction : str    
        correction method to use, either 'tajima' or 'none'
    kernel : str    
        kernel to use, either 'fident', 'lddt' or 'alntmscore'
    
    '''
    #check if the foldseek output is already there
    if os.path.exists(outfolder + 'res.m8') and overwrite == False:
        print('found foldseek output, skipping foldseek')
        alnres = outfolder + 'res.m8'
    else:
        alnres = foldseek2tree.runFoldseek_allvall_EZsearch(input_folder , outfolder + 'res.m8', foldseekpath = foldseekpath)
    
    if core == True:
        extract_core( alnres , alnres+'.core.csv',  hitthresh = .8 ,minthresh = .6  , structfolder = input_folder)
        corefolder = ''.join([ sub + '/' for sub in alnres.split('/')[:-1] ])+'core_structs/'
        if os.path.exists(outfolder + 'core.res.m8') and overwrite == False:
            print('found foldseek core output, skipping foldseek')
            alnres = outfolder + 'core.res.m8'
        else:
            alnres = foldseek2tree.runFoldseek_allvall_EZsearch(corefolder  , outfolder + 'core.res.m8', foldseekpath = foldseekpath  )
    
    
    res = pd.read_table(alnres , header = None )
    res[0] = res[0].map(lambda x :x.replace('.pdb', ''))
    res[1] = res[1].map(lambda x :x.replace('.pdb', ''))
    res.columns = 'query,target,fident,alnlen,mismatch,gapopen,qstart,qend,tstart,tend,evalue,bits,lddt,lddtfull,alntmscore'.split(',')
    ids = sorted(list( set(list(res['query'].unique()) + list(res['target'].unique()))))
    if swapids:
        res['numerical_query'] = res['query'].map(lambda x : ids.index(x))
        res['numerical_target'] = res['target'].map(lambda x : ids.index(x))
    
    pos = { protid : i for i,protid in enumerate(ids)}
    if swapids:
        ids = [ str(i) for i in range(len(ids))]

    matrices = { kernel:np.zeros((len(pos), len(pos))) for kernel in kernels} 

	#cast kernel columns to float
    for k in kernels:
        res[k] = res[k].astype(float )

    #calc kernel for tm, aln score, lddt
    for idx,row in res.iterrows():
        for k in matrices:
            matrices[k][pos[row['query']] , pos[row['target']]] += row[k]
            matrices[k][pos[row['target']] , pos[row['query']]] += row[k]
    trees = {}
    for i,k in enumerate(matrices):
        matrices[k] /= 2
        matrices[k] = 1-matrices[k]
        matrices[k] = np.clip(matrices[k], 0, 1)
        
        print(matrices[k], np.amax(matrices[k]), np.amin(matrices[k]) )
        if correction:
            if k == 'fident':
                factor = .93
            else:
                factor = 1
            matrices[k] = foldseek2tree.Tajima_dist(matrices[k], bfactor = factor)
        np.save( input_folder + k + '_distmat.npy' , matrices[k])
        distmat_txt = foldseek2tree.distmat_to_txt( ids , matrices[k] , outfolder + k + '_distmat.txt' )
        out_tree = foldseek2tree.runFastme(  fastmepath = fastmepath , clusterfile = distmat_txt )
        out_tree = foldseek2tree.postprocess(out_tree, input_folder + k + 'structblob_tree.nwk' , delta = delta)
        trees[k] = out_tree
    return res, trees

In [43]:
os.makedirs(datadir+'c1/ft1tree', exist_ok=True)
os.makedirs(datadir+'c2/ft1tree', exist_ok=True)
os.makedirs(datadir+'CRIMVLG/ft1tree', exist_ok=True)
os.makedirs(datadir+'c1/ft1corecut', exist_ok=True)
os.makedirs(datadir+'c2/ft1corecut', exist_ok=True)
os.makedirs(datadir+'CRIMVLG/ft1corecut', exist_ok=True)
results = {}
for folder in ['c1', 'c2', 'CRIMVLG']:
    #foldtree basic
    alnres, trees = structblob2tree(input_folder = datadir+folder +'/structs_fixed/', outfolder = datadir+folder+'/ft1tree/' , overwrite = False,
                fastmepath = 'fastme', quicktreepath = 'quicktree' , 
            foldseekpath = 'foldseek' , delta = 0.0001 ,
        correction = True ,  core = False 
        , hittresh = .8 , minthresh = .6  , swapids=True) 

    alnres_core , trees_core = structblob2tree(input_folder = datadir+folder +'/structs_fixed/' , outfolder = datadir+folder+'/ft1tree/' , overwrite = False,
                fastmepath = 'fastme', quicktreepath = 'quicktree' , 
            foldseekpath = 'foldseek' , delta = 0.0001 ,
        correction = True ,  core = True 
        , hittresh = .8 , minthresh = .6 , swapids=True)
    results[folder] = { 'alnres': alnres, 'trees': trees , 'alnres_core': alnres_core , 'trees_core': trees_core }

found foldseek output, skipping foldseek
[[0.     0.746  0.746  ... 0.8925 0.892  0.874 ]
 [0.746  0.     0.797  ... 0.91   0.87   0.9015]
 [0.746  0.797  0.     ... 0.903  0.9105 0.9   ]
 ...
 [0.8925 0.91   0.903  ... 0.     0.6885 0.6435]
 [0.892  0.87   0.9105 ... 0.6885 0.     0.724 ]
 [0.874  0.9015 0.9    ... 0.6435 0.724  0.    ]] 1.0 0.0

 . This analysis will run on 1 threads.

#  Analysing dataset 1

 . Computing tree...

 . Performing NNI...

 . Warning: 
	Explained variance = 0.019 (<0.90).
	Check your input data.

 . Time used 0h00m00s

   /-230
  |
  |--247
  |
  |         /-233
  |      /-|
  |     |   \-231
  |     |
  |   /-|      /-237
  |  |  |   /-|
  |  |  |  |   \-235
  |  |   \-|
  |  |     |   /-236
  |  |     |  |
  |  |      \-|      /-232
  |  |        |   /-|
--|  |        |  |   \-229
  |  |         \-|
  |  |           |   /-246
  |  |           |  |
  |  |            \-|   /-239
  |  |              |  |
  |  |              |  |      /-238
  |  |         

processed: 15:   6%|▌         | 14/248 [00:00<00:02, 79.17it/s]

[[0.         0.21774194 0.22983871 0.23790323 0.24193548 0.29435484
  0.30645161 0.31451613 0.33064516 0.33064516 0.33467742 0.33467742
  0.33467742 0.33467742 0.33467742 0.33870968 0.33870968 0.35080645
  0.35080645 0.35080645 0.37096774 0.37903226 0.39516129 0.39919355
  0.41129032 0.42741935 0.45967742 0.48790323 0.48790323 0.50806452
  0.56048387 0.64112903 0.67741935 0.72177419 0.73387097 0.73387097
  0.73387097 0.73387097 0.73387097 0.73387097 0.73387097 0.73387097
  0.73387097 0.73387097 0.73387097 0.73387097 0.73387097 0.73387097
  0.73387097 0.73387097 0.73387097 0.73387097 0.73387097 0.73387097
  0.73387097 0.73387097 0.73387097 0.73387097 0.73387097 0.73387097
  0.73387097 0.73387097 0.73387097 0.73387097 0.73387097 0.73387097
  0.73387097 0.73387097 0.73387097 0.73387097 0.73387097 0.73387097
  0.73387097 0.73387097 0.73387097 0.73387097 0.72983871 0.72983871
  0.72983871 0.72580645 0.72580645 0.72580645 0.72580645 0.72580645
  0.72580645 0.72580645 0.72580645 0.71774194 0.

processed: 71:  28%|██▊       | 70/248 [00:00<00:02, 88.38it/s]

[[0.         0.03225806 0.03225806 ... 0.02419355 0.01612903 0.00403226]]                                                query  \
12997  IleRS_AF_Euk_Ustilago_maydis_521_gene23568123   
12998  IleRS_AF_Euk_Ustilago_maydis_521_gene23568123   
12999  IleRS_AF_Euk_Ustilago_maydis_521_gene23568123   
13000  IleRS_AF_Euk_Ustilago_maydis_521_gene23568123   
13001  IleRS_AF_Euk_Ustilago_maydis_521_gene23568123   
...                                              ...   
13237  IleRS_AF_Euk_Ustilago_maydis_521_gene23568123   
13238  IleRS_AF_Euk_Ustilago_maydis_521_gene23568123   
13239  IleRS_AF_Euk_Ustilago_maydis_521_gene23568123   
13240  IleRS_AF_Euk_Ustilago_maydis_521_gene23568123   
13241  IleRS_AF_Euk_Ustilago_maydis_521_gene23568123   

                                                  target  fident  alnlen  \
12997      IleRS_AF_Euk_Ustilago_maydis_521_gene23568123   1.000    1083   
12998               IleRS_AF_Mito_Homo_sapiens_gene55699   0.352    1100   
12999  IleRS_AF_Euk_Cyani

processed: 90:  36%|███▋      | 90/248 [00:01<00:01, 88.29it/s]

[[0.         0.16129032 0.18951613 0.2016129  0.25       0.26612903
  0.27419355 0.28225806 0.28225806 0.28225806 0.28225806 0.28225806
  0.29032258 0.29435484 0.29435484 0.29435484 0.29435484 0.2983871
  0.32258065 0.32258065 0.33064516 0.33870968 0.33870968 0.33870968
  0.34677419 0.35080645 0.35080645 0.35080645 0.35887097 0.41129032
  0.45967742 0.47580645 0.53225806 0.53629032 0.53629032 0.53629032
  0.53629032 0.53629032 0.53629032 0.54032258 0.54032258 0.54032258
  0.54032258 0.54032258 0.54032258 0.54032258 0.54032258 0.54032258
  0.54032258 0.54032258 0.54032258 0.54032258 0.54032258 0.54032258
  0.54032258 0.54032258 0.54032258 0.54032258 0.54032258 0.54032258
  0.54032258 0.54032258 0.54032258 0.54032258 0.54032258 0.54032258
  0.54032258 0.54032258 0.54032258 0.54032258 0.54032258 0.54032258
  0.54032258 0.54032258 0.54032258 0.54032258 0.54032258 0.54032258
  0.54032258 0.54032258 0.54032258 0.54032258 0.54032258 0.54032258
  0.54032258 0.54032258 0.54032258 0.54032258 0.5

processed: 117:  47%|████▋     | 117/248 [00:01<00:01, 87.68it/s]

[[0.         0.01209677 0.01612903 ... 0.02419355 0.02016129 0.01209677]]                                                    query  \
24288  ValRS_AF_Euk_Plasmodium_knowlesi_strain_H_gene...   
24289  ValRS_AF_Euk_Plasmodium_knowlesi_strain_H_gene...   
24290  ValRS_AF_Euk_Plasmodium_knowlesi_strain_H_gene...   
24291  ValRS_AF_Euk_Plasmodium_knowlesi_strain_H_gene...   
24292  ValRS_AF_Euk_Plasmodium_knowlesi_strain_H_gene...   
...                                                  ...   
24529  ValRS_AF_Euk_Plasmodium_knowlesi_strain_H_gene...   
24530  ValRS_AF_Euk_Plasmodium_knowlesi_strain_H_gene...   
24531  ValRS_AF_Euk_Plasmodium_knowlesi_strain_H_gene...   
24532  ValRS_AF_Euk_Plasmodium_knowlesi_strain_H_gene...   
24533  ValRS_AF_Euk_Plasmodium_knowlesi_strain_H_gene...   

                                                  target  fident  alnlen  \
24288  ValRS_AF_Euk_Plasmodium_knowlesi_strain_H_gene...   1.000    1070   
24289  ValRS_AF_Euk_Trypanosoma_brucei_brucei_TREU927

processed: 179:  72%|███████▏  | 178/248 [00:02<00:00, 88.25it/s]

[[0.         0.0766129  0.11693548 ... 0.04435484 0.03629032 0.02016129]]                                                    query  \
39525  IleRS_AF_Bact_Thermus_thermophilus_HB8_gene316...   
39526  IleRS_AF_Bact_Thermus_thermophilus_HB8_gene316...   
39527  IleRS_AF_Bact_Thermus_thermophilus_HB8_gene316...   
39528  IleRS_AF_Bact_Thermus_thermophilus_HB8_gene316...   
39529  IleRS_AF_Bact_Thermus_thermophilus_HB8_gene316...   
...                                                  ...   
39756  IleRS_AF_Bact_Thermus_thermophilus_HB8_gene316...   
39757  IleRS_AF_Bact_Thermus_thermophilus_HB8_gene316...   
39758  IleRS_AF_Bact_Thermus_thermophilus_HB8_gene316...   
39759  IleRS_AF_Bact_Thermus_thermophilus_HB8_gene316...   
39760  IleRS_AF_Bact_Thermus_thermophilus_HB8_gene316...   

                                                  target  fident  alnlen  \
39525  IleRS_AF_Bact_Thermus_thermophilus_HB8_gene316...   1.000    1043   
39526                        IleRS_PDB_Bact_T_therm_1

processed: 198:  79%|███████▉  | 197/248 [00:02<00:00, 88.33it/s]

[[0.         0.03225806 0.03629032 ... 0.03225806 0.03225806 0.00806452]]                                       query  \
44179  IleRS_AF_Mito_Homo_sapiens_gene55699   
44180  IleRS_AF_Mito_Homo_sapiens_gene55699   
44181  IleRS_AF_Mito_Homo_sapiens_gene55699   
44182  IleRS_AF_Mito_Homo_sapiens_gene55699   
44183  IleRS_AF_Mito_Homo_sapiens_gene55699   
...                                     ...   
44414  IleRS_AF_Mito_Homo_sapiens_gene55699   
44415  IleRS_AF_Mito_Homo_sapiens_gene55699   
44416  IleRS_AF_Mito_Homo_sapiens_gene55699   
44417  IleRS_AF_Mito_Homo_sapiens_gene55699   
44418  IleRS_AF_Mito_Homo_sapiens_gene55699   

                                                  target  fident  alnlen  \
44179               IleRS_AF_Mito_Homo_sapiens_gene55699   1.000    1012   
44180    IleRS_AF_Mito_Drosophila_melanogaster_gene39762   0.374     999   
44181  IleRS_AF_Euk_Cyanidioschyzon_merolae_strain_10...   0.354    1110   
44182      IleRS_AF_Euk_Ustilago_maydis_521_gene23568123 

processed: 239:  96%|█████████▌| 238/248 [00:02<00:00, 88.29it/s]

[[0.         0.04435484 0.05645161 ... 0.03225806 0.03225806 0.03225806]]                                                    query  \
54254  LeuRS-A_AF_Euk_Drosophila_melanogaster_gene326262   
54255  LeuRS-A_AF_Euk_Drosophila_melanogaster_gene326262   
54256  LeuRS-A_AF_Euk_Drosophila_melanogaster_gene326262   
54257  LeuRS-A_AF_Euk_Drosophila_melanogaster_gene326262   
54258  LeuRS-A_AF_Euk_Drosophila_melanogaster_gene326262   
...                                                  ...   
54487  LeuRS-A_AF_Euk_Drosophila_melanogaster_gene326262   
54488  LeuRS-A_AF_Euk_Drosophila_melanogaster_gene326262   
54489  LeuRS-A_AF_Euk_Drosophila_melanogaster_gene326262   
54490  LeuRS-A_AF_Euk_Drosophila_melanogaster_gene326262   
54491  LeuRS-A_AF_Euk_Drosophila_melanogaster_gene326262   

                                                  target  fident  alnlen  \
54254  LeuRS-A_AF_Euk_Drosophila_melanogaster_gene326262   1.000    1182   
54255              LeuRS-A_AF_Euk_Homo_sapiens_gene51

  0%|          | 0/248 [00:00<?, ?it/s]/work/FAC/FBM/DBC/cdessim2/default/dmoi/miniconda3/envs/torch/lib/python3.12/site-packages/Bio/PDB/PDBParser.py:388: PDBConstructionWarning: Ignoring unrecognized record 'END' at line 8725
  warnings.warn(
processed: 1:   0%|          | 0/248 [00:00<?, ?it/s]/work/FAC/FBM/DBC/cdessim2/default/dmoi/miniconda3/envs/torch/lib/python3.12/site-packages/Bio/PDB/PDBParser.py:388: PDBConstructionWarning: Ignoring unrecognized record 'END' at line 6865
  warnings.warn(
processed: 2:   1%|          | 2/248 [00:00<00:28,  8.64it/s]/work/FAC/FBM/DBC/cdessim2/default/dmoi/miniconda3/envs/torch/lib/python3.12/site-packages/Bio/PDB/PDBParser.py:388: PDBConstructionWarning: Ignoring unrecognized record 'END' at line 7438
  warnings.warn(
processed: 3:   1%|          | 2/248 [00:00<00:28,  8.64it/s]/work/FAC/FBM/DBC/cdessim2/default/dmoi/miniconda3/envs/torch/lib/python3.12/site-packages/Bio/PDB/PDBParser.py:388: PDBConstructionWarning: Ignoring unrecognized recor

found foldseek core output, skipping foldseek
[[0.     0.755  0.615  ... 0.8675 0.8635 0.832 ]
 [0.755  0.     0.795  ... 0.861  0.8185 0.88  ]
 [0.615  0.795  0.     ... 0.895  0.9235 0.869 ]
 ...
 [0.8675 0.861  0.895  ... 0.     0.53   1.    ]
 [0.8635 0.8185 0.9235 ... 0.53   0.     1.    ]
 [0.832  0.88   0.869  ... 1.     1.     0.    ]] 1.0 0.0

 . This analysis will run on 1 threads.

#  Analysing dataset 1

 . Computing tree...

 . Performing NNI...

 . Warning: 
	Explained variance = 0.315 (<0.90).
	Check your input data.

 . Time used 0h00m00s

   /-247
  |
  |   /-122
  |--|
  |  |   /-124
  |   \-|
  |     |   /-100
  |      \-|
--|        |   /-110
  |         \-|
  |           |   /-181
  |            \-|
  |               \-123
  |
  |   /-102
  |  |
   \-|   /-218
     |  |
      \-|   /-207
        |  |
         \-|   /-193
           |  |
            \-|   /-204
              |  |
               \-|   /-106
                 |  |
                  \-|   /-103
        

processed: 161:  54%|█████▍    | 160/295 [00:02<00:01, 69.91it/s]

[[0.         0.00677966 0.00677966 0.00677966 0.01016949 0.01016949
  0.01016949 0.01016949 0.01016949 0.01355932 0.01355932 0.01355932
  0.01694915 0.01694915 0.01694915 0.01694915 0.01694915 0.02033898
  0.03050847 0.03728814 0.04067797 0.04067797 0.06101695 0.06101695
  0.06101695 0.07457627 0.09152542 0.09491525 0.10508475 0.10847458
  0.11186441 0.11186441 0.11864407 0.11864407 0.13559322 0.13898305
  0.14915254 0.15932203 0.20338983 0.21016949 0.23050847 0.23389831
  0.38305085 0.45762712 0.4779661  0.4779661  0.4779661  0.4779661
  0.48135593 0.48135593 0.48135593 0.48135593 0.48135593 0.48135593
  0.48135593 0.48135593 0.48135593 0.48135593 0.48135593 0.48135593
  0.48135593 0.48135593 0.48474576 0.48474576 0.48474576 0.48474576
  0.48474576 0.48474576 0.48474576 0.48474576 0.48474576 0.48474576
  0.48474576 0.48474576 0.48474576 0.48474576 0.48474576 0.48474576
  0.48474576 0.48474576 0.48474576 0.48474576 0.48474576 0.48474576
  0.48474576 0.48474576 0.48474576 0.48474576 0.4

processed: 1:   0%|          | 0/294 [00:00<?, ?it/s]/work/FAC/FBM/DBC/cdessim2/default/dmoi/miniconda3/envs/torch/lib/python3.12/site-packages/Bio/PDB/PDBParser.py:388: PDBConstructionWarning: Ignoring unrecognized record 'END' at line 12385
  warnings.warn(
processed: 2:   1%|          | 2/294 [00:00<00:25, 11.45it/s]/work/FAC/FBM/DBC/cdessim2/default/dmoi/miniconda3/envs/torch/lib/python3.12/site-packages/Bio/PDB/PDBParser.py:388: PDBConstructionWarning: Ignoring unrecognized record 'END' at line 7927
  warnings.warn(
processed: 3:   1%|          | 2/294 [00:00<00:25, 11.45it/s]/work/FAC/FBM/DBC/cdessim2/default/dmoi/miniconda3/envs/torch/lib/python3.12/site-packages/Bio/PDB/PDBParser.py:388: PDBConstructionWarning: Ignoring unrecognized record 'END' at line 7265
  warnings.warn(
processed: 4:   1%|▏         | 4/294 [00:00<00:21, 13.71it/s]/work/FAC/FBM/DBC/cdessim2/default/dmoi/miniconda3/envs/torch/lib/python3.12/site-packages/Bio/PDB/PDBParser.py:388: PDBConstructionWarning: Igno

found foldseek core output, skipping foldseek
[[0.     0.574  0.343  ... 0.91   0.852  0.8785]
 [0.574  0.     0.56   ... 0.871  0.863  0.9005]
 [0.343  0.56   0.     ... 0.907  0.8545 0.8695]
 ...
 [0.91   0.871  0.907  ... 0.     0.603  0.563 ]
 [0.852  0.863  0.8545 ... 0.603  0.     0.61  ]
 [0.8785 0.9005 0.8695 ... 0.563  0.61   0.    ]] 1.0 0.0

 . This analysis will run on 1 threads.

#  Analysing dataset 1

 . Computing tree...

 . Performing NNI...

 . Warning: 
	Explained variance = 0.018 (<0.90).
	Check your input data.

 . Time used 0h00m00s

   /-293
  |
  |   /-284
  |  |
  |  |      /-289
  |--|   /-|
  |  |  |   \-286
  |  |  |
  |   \-|      /-285
  |     |   /-|
  |     |  |   \-283
  |      \-|
  |        |   /-287
  |         \-|
  |           |   /-290
  |            \-|
  |               \-282
  |
  |         /-274
  |      /-|
  |     |  |   /-279
  |     |   \-|
  |     |     |   /-288
  |     |      \-|
  |   /-|         \-273
  |  |  |
--|  |  |      /-276
  


 . Error: Invalid distance matrix : numerical value expected for taxon '23' instead of 'nan'.


[[0.     0.652  0.748  ... 0.8625 0.842  0.8615]
 [0.652  0.     0.79   ... 0.89   0.921  0.9205]
 [0.748  0.79   0.     ... 0.8685 0.924  0.8945]
 ...
 [0.8625 0.89   0.8685 ... 0.     0.909  0.877 ]
 [0.842  0.921  0.924  ... 0.909  0.     0.6835]
 [0.8615 0.9205 0.8945 ... 0.877  0.6835 0.    ]] 0.957 0.0

 . This analysis will run on 1 threads.

#  Analysing dataset 1

 . Computing tree...

 . Performing NNI...

 . Warning: 
	Explained variance = 0.565 (<0.90).
	Check your input data.

 . Time used 0h00m00s

   /-46
  |
  |   /-35
  |--|
  |   \-30
--|
  |   /-32
  |  |
  |  |      /-29
  |  |   /-|
   \-|  |  |   /-45
     |  |   \-|
     |  |      \-28
     |  |
      \-|      /-40
        |   /-|
        |  |   \-36
        |  |
        |  |      /-24
        |  |   /-|
         \-|  |  |   /-25
           |  |   \-|
           |  |     |   /-34
           |  |      \-|
           |  |        |   /-31
           |  |         \-|
            \-|            \-26
              |
  

  0%|          | 0/47 [00:00<?, ?it/s]/work/FAC/FBM/DBC/cdessim2/default/dmoi/miniconda3/envs/torch/lib/python3.12/site-packages/Bio/PDB/PDBParser.py:388: PDBConstructionWarning: Ignoring unrecognized record 'END' at line 2259
  warnings.warn(
processed: 1:   2%|▏         | 1/47 [00:00<00:08,  5.58it/s]/work/FAC/FBM/DBC/cdessim2/default/dmoi/miniconda3/envs/torch/lib/python3.12/site-packages/Bio/PDB/PDBParser.py:388: PDBConstructionWarning: Ignoring unrecognized record 'END' at line 2434
  warnings.warn(
processed: 2:   2%|▏         | 1/47 [00:00<00:08,  5.58it/s]/work/FAC/FBM/DBC/cdessim2/default/dmoi/miniconda3/envs/torch/lib/python3.12/site-packages/Bio/PDB/PDBParser.py:388: PDBConstructionWarning: Ignoring unrecognized record 'END' at line 2364
  warnings.warn(
processed: 3:   4%|▍         | 2/47 [00:00<00:08,  5.58it/s]/work/FAC/FBM/DBC/cdessim2/default/dmoi/miniconda3/envs/torch/lib/python3.12/site-packages/Bio/PDB/PDBParser.py:388: PDBConstructionWarning: Ignoring unrecognized r

found foldseek core output, skipping foldseek
[[0.     0.644  0.744  ... 0.8665 0.826  0.905 ]
 [0.644  0.     0.7925 ... 0.886  0.868  0.936 ]
 [0.744  0.7925 0.     ... 0.8945 0.916  0.849 ]
 ...
 [0.8665 0.886  0.8945 ... 0.     0.888  0.891 ]
 [0.826  0.868  0.916  ... 0.888  0.     0.688 ]
 [0.905  0.936  0.849  ... 0.891  0.688  0.    ]] 0.9755 0.0

 . This analysis will run on 1 threads.

#  Analysing dataset 1

 . Computing tree...

 . Performing NNI...

 . Warning: 
	Explained variance = 0.252 (<0.90).
	Check your input data.

 . Time used 0h00m00s

   /-30
  |
  |--46
  |
--|   /-35
  |  |
  |  |         /-26
  |  |      /-|
  |  |     |   \-32
   \-|   /-|
     |  |  |   /-45
     |  |   \-|
     |  |      \-28
     |  |
     |  |      /-40
      \-|   /-|
        |  |   \-36
        |  |
        |  |         /-25
        |  |      /-|
        |  |     |   \-24
         \-|   /-|
           |  |  |   /-34
           |  |   \-|
           |  |      \-29
           |  |
      

In [45]:
#save the dataframes 
for folder in results:
	for key in results[folder]:
		if key.startswith('alnres'):
			results[folder][key].to_csv(datadir+folder+'/ft1tree/' + key + '.csv')
#reformat the tree files with the name mapper
import ete3

for folder in results:
	for key in results[folder]:
		df = results[folder]['alnres']
		mapper = dict( zip( df['numerical_query'] , df['query'] ))
		if key.startswith('trees'):
			for k in results[folder][key]:
				t = ete3.Tree(results[folder][key][k])
				print(k , results[folder][key][k])
				for leaf in t:
					leaf.name = mapper[int(leaf.name)]
				print(t)
				t.write(outfile =results[folder][key][k]+'.rename.nwk', format = 0 )


fident /work/FAC/FBM/DBC/cdessim2/default/dmoi/projects/aars/aarsonline.github.io/struct_trees/c1/structs_fixed/fidentstructblob_tree.nwk

   /-ValRS_PDB_Bact_T_therm_1GAX
  |
  |   /-LeuRS-A_AF_Euk_Neurospora_crassa_OR74A_gene3879366
  |--|
  |  |   /-LeuRS-A_PDB_Arch_P_hori_1WKB
  |   \-|
  |     |   /-IleRS_AF_Bact_Orientia_tsutsugamushi_str_Ikeda_gene66653313
  |      \-|
--|        |   /-IleRS_AF_Mito_Homo_sapiens_gene55699
  |         \-|
  |           |   /-TrpRS_AF_Bact_Escherichia_coli_O157:H7_str._Sakai_gene915919
  |            \-|
  |               \-LeuRS-A_AF_Euk_Saccharomyces_cerevisiae_S288C_gene855943
  |
  |   /-IleRS_AF_Bact_Thermus_thermophilus_HB8_gene3168241
  |  |
   \-|   /-TyrRS_AF_Mito_Aspergillus_fumigatus_Af293_gene3509181
     |  |
      \-|   /-TyrRS_AF_Bact_Lactococcus_lactis_subsp_cremoris_KW2_gene61108704
        |  |
         \-|   /-TrpRS_AF_Mito_Homo_sapiens_gene10352
           |  |
            \-|   /-TyrRS_AF_Bact_Bifidobacterium_animalis_subsp_la

In [16]:
import shutil
#copy the cores and set things up for the snakemake pipeline


os.makedirs(datadir+'mltrees/', exist_ok=True)
for fam in ['c1', 'c2', 'CRIMVLG']:
	input_folder = datadir+folder +'/ft1tree/'
	cpdir = input_folder+'core_structs/'
	os.makedirs(datadir+'mltrees/'+fam, exist_ok=True)
	os.makedirs(datadir+'mltrees/'+fam+'/structs', exist_ok=True)
	#copy the core structures
	for f in glob.glob(cpdir+'/*'):
		#only copy the pdb files if they are not already there
		if not os.path.exists(datadir+'mltrees/'+fam+'/structs/'+f.split('/')[-1]):
			shutil.copy(f, datadir+'mltrees/'+fam+'/structs/')
	with open( datadir+'mltrees/'+fam+'/identifiers.txt' , 'w') as f:
		for i in range(len(glob.glob(cpdir+'/*'))):
			f.write(str(i)+'\n')

	#write a dummy finalset.csv file to each folder
	with open( datadir+'mltrees/'+fam+'/finalset.csv' , 'w') as f:
		f.write('pdb,chain,uniprot\n')
		f.write('dummy,dummy,dummy\n')
	